version: '2.4'

services:
  nginx:
    image: nginx:revproxy-tmpl
    container_name: nginx
    build: .
    env_file:
      - ./defaults.env
    ports:
      - "${IP}:${DOCKER_HTTP}:80"
      - "${IP}:${DOCKER_HTTPS}:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH}/htpasswd:/etc/nginx/htpasswd:ro
    privileged: true
    restart: always
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 10s
      timeout: 6s
      retries: 4

  docker-gen:
    image: jwilder/docker-gen
    container_name: docker-gen
    depends_on:
      nginx:
        condition: service_healthy
    env_file:
      - ./defaults.env
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    entrypoint: /usr/bin/docker-gen
    command: |
      -notify-sighup nginx -watch -wait 5s:30s \
        /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    privileged: true
    restart: always

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    env_file:
      - ./defaults.env
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DEFAULT_EMAIL: ${DEFAULT_EMAIL}
    privileged: true
    restart: always

networks:
  webproxy:
    external: True
